service: nuxt-serverless-at-edge

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  logRetentionInDays: 3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:logs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'log-group:/aws/lambda/*:*:*'
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
          Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - "Ref" : "ServerlessDeploymentBucket"

plugins:
  - serverless-plugin-cloudfront-lambda-edge
  - serverless-scriptable-plugin  

custom:
   scriptHooks:
     before:package:createDeploymentArtifacts: npm run build
     before:invoke:local:invoke: npm run build
     before:deploy:deploy: 
       - aws s3 cp --recursive ./.nuxt/dist/client/ s3://nuxt-serverless-at-edge/_nuxt/ --cache-control "max-age=31536000,public,immutable"
       - aws s3 cp --recursive ./static/ s3://nuxt-serverless-at-edge/ --exclude "README.md" --cache-control "max-age=31536000,public,immutable"
     before:deploy:finalize: aws cloudfront create-invalidation --distribution-id ${cf:nuxt-serverless-at-edge-dev.NuxtEdgeDistributionId} --paths "/*"

package:
  individually: true
  excludeDevDependencies: true

functions:
  render:
    handler: server/edge.handler
    memorySize: 512
    timeout: 10
    lambdaAtEdge:
      distribution: 'NuxtEdgeDistribution'
      eventType: 'origin-request'
    package:
      exclude:
        - "assets/**"
        - "components/**"
        - "layouts/**"
        - "components/**"
        - "middleware/**"
        - "pages/**"
        - "plugins/**"
      include:
        - ".nuxt/**"
        - "server/edge.js"
        - "nuxt.config.js"

resources:
  Resources:
    NuxtEdgeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: nuxt-serverless-at-edge
    NuxtEdgeBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: { Ref: NuxtEdgeBucket }
        PolicyDocument:
          Statement:
            -
              Action:
                - "s3:GetObject"
              Effect: Allow
              Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { Ref : NuxtEdgeBucket }, "/*" ] ]  }
              Principal:
                AWS: { "Fn::Join" : [" ", ["arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity", { Ref: NuxtEdgeOriginAccessIdentity } ] ] }
    NuxtEdgeOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: "CloudFrontOriginAccessIdentity for ${self:service}-${self:provider.stage}"
    NuxtEdgeDistribution:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          DefaultCacheBehavior:
            TargetOriginId: 'NuxtEdgeBucketOrigin'
            ViewerProtocolPolicy: 'redirect-to-https'
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
            Compress: true
            ForwardedValues:
              QueryString: true
            AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          DefaultRootObject: ''
          Enabled: true
          PriceClass: 'PriceClass_100'
          HttpVersion: 'http2'
          IPV6Enabled: false
          Origins:
            -
              Id: 'NuxtEdgeBucketOrigin'
              DomainName: { 'Fn::GetAtt': [ NuxtEdgeBucket, DomainName ] }
              S3OriginConfig:
                OriginAccessIdentity: { "Fn::Join" : ["", ["origin-access-identity/cloudfront/", { Ref: NuxtEdgeOriginAccessIdentity } ] ]  }
          CacheBehaviors:
            - PathPattern: '*.jpg'
              AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              TargetOriginId: NuxtEdgeBucketOrigin
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: 'https-only'
              MinTTL: 31536000
              DefaultTTL: 31536000
              MaxTTL: 31536000
              Compress: true
            - PathPattern: '*.css'
              AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              TargetOriginId: NuxtEdgeBucketOrigin
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: 'https-only'
              MinTTL: 31536000
              DefaultTTL: 31536000
              MaxTTL: 31536000
              Compress: true
            - PathPattern: '*.js'
              AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              TargetOriginId: NuxtEdgeBucketOrigin
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: 'https-only'
              MinTTL: 31536000
              DefaultTTL: 31536000
              MaxTTL: 31536000
              Compress: true
            - PathPattern: '*.map'
              AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              TargetOriginId: NuxtEdgeBucketOrigin
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: 'https-only'
              MinTTL: 31536000
              DefaultTTL: 31536000
              MaxTTL: 31536000
              Compress: true
            - PathPattern: '*.ico'
              AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              TargetOriginId: NuxtEdgeBucketOrigin
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: 'https-only'
              MinTTL: 31536000
              DefaultTTL: 31536000
              MaxTTL: 31536000
              Compress: true
            - PathPattern: '*.png'
              AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              TargetOriginId: NuxtEdgeBucketOrigin
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: 'https-only'
              MinTTL: 31536000
              DefaultTTL: 31536000
              MaxTTL: 31536000
              Compress: true

  Outputs:
      NuxtEdgeDistributionDomain:
        Value:
          'Fn::GetAtt': [ NuxtEdgeDistribution, DomainName ]
        Export:
          Name: NuxtEdgeDistributionDomain
      NuxtEdgeDistributionId:
        Value:
          Ref: NuxtEdgeDistribution
        Export:
          Name: NuxtEdgeDistributionId   